Repository Netcracker/qubership-jaeger, pull requests merged in 2025-03, with the labels that each got.

#33 Fix affinity for Integration Tests component
  charts/qubership-jaeger/Chart.yaml
  charts/qubership-jaeger/templates/integration-tests/deployment.yaml
Labels: bug

#36 Feature: spark-dependencies cron-job
  charts/qubership-jaeger/.editorconfig
  charts/qubership-jaeger/templates/_helpers.tpl
  charts/qubership-jaeger/templates/spark-dependencies/role-binding.yaml
  charts/qubership-jaeger/templates/spark-dependencies/role.yaml
  charts/qubership-jaeger/templates/spark-dependencies/service-account.yaml
  charts/qubership-jaeger/templates/spark-dependencies/spark-cron-job.yaml
  charts/qubership-jaeger/templates/spark-dependencies/truststore-secret.yaml
  charts/qubership-jaeger/values.yaml
Labels: enhancement

#31 Tests refactor timestamp handling to ensure 16-character format
  integration-tests/robot/tests/libs/JaegerLibrary.py
Labels: bug

#35 Split ingresses for collector
  charts/qubership-jaeger/templates/_helpers.tpl
  charts/qubership-jaeger/templates/collector/ingress-grpc.yaml
  charts/qubership-jaeger/templates/collector/ingress-http.yaml
  charts/qubership-jaeger/templates/collector/ingress.yaml
  charts/qubership-jaeger/values.yaml
  docs/installation.md
Labels: documentation, enhancement

#40 feat: Add Docker build configuration and Jaeger release workflow
  .github/docker-build-config.json
  .github/workflows/jaeger-release.yaml
Labels: enhancement

#41 feat: Update Docker build configuration and workflow for improved component loading and platform support
  .github/docker-build-config.json
  .github/workflows/jaeger-release.yaml
Labels: bug, enhancement

#44 feat: Add asset upload job for Helm charts and documentation
  .github/assets-config.yml
  .github/workflows/jaeger-release.yaml
Labels: bug, documentation, enhancement

#48 feat: Add PR auto-assignment workflow and CODEOWNERS configuration
  .github/CODEOWNERS
  .github/pr-assigner-config.yml
  .github/workflows/pr-assigner.yml
Labels: enhancement

#54 Chores
  .editorconfig
  .github/CODEOWNERS
  .github/linters/.golangci.yml
  .github/pr-assigner-config.yml
  .github/workflows/pr-assigner.yml
  README.md
  charts/qubership-jaeger/templates/spark-dependencies/spark-cron-job.yaml
Labels: bug

#37 Envoy audit log format to JSON
  .github/CODEOWNERS
  charts/qubership-jaeger/templates/query/auth-proxy/proxy-secret-config.yaml
  charts/qubership-jaeger/values.yaml
  docs/installation.md
  docs/observability.md
Labels: bug, enhancement

#63 feat: pr-assigner template updated
  .github/workflows/pr-assigner.yml
Labels: bug, enhancement
